name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: sudo apt-get install -y graphviz 
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement de graphviz
      run: ./graphiz1.sh g1
    - name: upload resultat
      uses: actions/upload-artifact@v4
      with:
        name: upload g1
        path: g1.svg
